name: Skia Native Build Matrix

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # platform: [windows, linux, wasm]
        platform: [wasm]
        # build_type: [release, debug]
        build_type: [release]
        library_type: [static, dynamic]

    runs-on: ${{
      matrix.platform == 'windows' && 'windows-latest' ||
      matrix.platform == 'linux' && 'ubuntu-latest' ||
      matrix.platform == 'macos' && 'macos-latest' ||
      matrix.platform == 'wasm' && 'ubuntu-latest' }}

    env:
      ENV_PLATFORM: ${{ matrix.platform }}
      ENV_BUILD_TYPE: ${{ matrix.build_type }}
      ENV_LIBRARY_TYPE: ${{ matrix.library_type }}
      ENV_BUILD_DIR: skia/out/build

    name: ${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache depot_tools
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/depot_tools
          key: depot_tools-${{ matrix.platform }}-${{ hashFiles('scripts/install-deps-*') }}

      - name: Install dependencies for ${{ matrix.platform }}
        if: matrix.platform != 'windows'
        shell: bash
        run: |
          chmod +x ./scripts/install-deps-${{ matrix.platform }}.sh
          ./scripts/install-deps-${{ matrix.platform }}.sh

      - name: Install dependencies for ${{ matrix.platform }}
        if: matrix.platform == 'windows'
        shell: pwsh
        run: ./scripts/install-deps-windows.ps1

      - name: Setup depot_tools
        shell: bash
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/depot_tools" ]; then
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            # Optional: pin a known revision
            # cd depot_tools
            # git checkout <known-good-sha>
            # cd ..
          fi
          echo "DEPOT_TOOLS=$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_ENV
          echo "PATH=$GITHUB_WORKSPACE/depot_tools:$PATH" >> $GITHUB_ENV

      - name: Clean build output
        shell: bash
        run: rm -rf "$ENV_BUILD_DIR"

      - name: Build Skia ${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}
        shell: bash
        run: |
          chmod +x ./scripts/build-skia.sh
          ./scripts/build-skia.sh

      - name: Zip built binaries
        shell: bash
        run: |
          zip_name="skia-${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}.zip"
          if [ -d "$ENV_BUILD_DIR" ]; then
            echo "Zipping contents of $ENV_BUILD_DIR into $zip_name"
            zip -r "$zip_name" "$ENV_BUILD_DIR"
          else
            echo "❌ Directory $ENV_BUILD_DIR does not exist. Skipping zip."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skia-${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}
          path: "./skia-${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}.zip"
