name: Skia Build Matrix

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/native-build.yml"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows, linux]
        build_type: [release, debug]
        library_type: [static, dynamic]

    runs-on: ${{
      matrix.platform == 'windows' && 'windows-latest' ||
      matrix.platform == 'linux' && 'ubuntu-latest' ||
      matrix.platform == 'macos' && 'macos-latest' }}

    env:
      BUILD_DIR: skia/out/build

    name: ${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache depot_tools
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/depot_tools
          key: depot_tools-${{ matrix.platform }}-${{ hashFiles('scripts/install-deps-*') }}

      - name: Install dependencies for ${{ matrix.platform }}
        if: matrix.platform != 'windows'
        shell: bash
        run: |
          chmod +x ./scripts/install-deps-${{ matrix.platform }}.sh
          ./scripts/install-deps-${{ matrix.platform }}.sh

      - name: Install dependencies for ${{ matrix.platform }}
        if: matrix.platform == 'windows'
        shell: pwsh
        run: ./scripts/install-deps-windows.ps1

      - name: Setup depot_tools
        shell: bash
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/depot_tools" ]; then
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            # Optional: pin a known revision
            # cd depot_tools
            # git checkout <known-good-sha>
            # cd ..
          fi
          echo "DEPOT_TOOLS=$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_ENV
          echo "PATH=$GITHUB_WORKSPACE/depot_tools:$PATH" >> $GITHUB_ENV

      - name: Clean build output
        shell: bash
        run: rm -rf "$BUILD_DIR"

      - name: Build Skia ${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}
        shell: bash
        run: |
          chmod +x ./scripts/build-skia.sh
          ./scripts/build-skia.sh "${{ matrix.platform }}" "${{ matrix.build_type }}" "${{ matrix.library_type }}"

      - name: Zip built binaries
        shell: bash
        run: |
          zip_name="skia-${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}.zip"
          if [ -d "$BUILD_DIR" ]; then
            echo "Zipping contents of $BUILD_DIR into $zip_name"
            zip -r "$zip_name" "$BUILD_DIR"
          else
            echo "❌ Directory $BUILD_DIR does not exist. Skipping zip."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skia-${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}
          path: "./skia-${{ matrix.platform }}-${{ matrix.build_type }}-${{ matrix.library_type }}.zip"

  release:
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3

      - name: Download all build artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release by GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
