# .github/workflows/release.yml

name: Create Release

on:
  workflow_run:
    workflows:
      - Skia Native Build Matrix
      - Skia Android Build Matrix
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download native artifacts
        uses: actions/download-artifact@v4
        with:
          name: native-artifacts
          path: artifacts/native

      - name: Download android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-artifacts
          path: artifacts/android

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release after builds
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
