# .github/workflows/release.yml

name: Create Release

on:
  workflow_run:
    workflows:
      - Skia Native Build Matrix
      - Skia Android Build Matrix
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Extract inner ZIPs (built binaries)
        run: |
          mkdir extracted
          # Unzip each artifact ZIP to get inner skia-*.zip files
          for artifact_zip in artifacts/*.zip; do
            unzip -o "$artifact_zip" -d extracted/
          done

      - name: List extracted files for debug
        run: ls -l extracted/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release after builds
          files: extracted/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
